E_Commerce_Website/urls.py
from django.contrib import admin
from django.urls import path, include


from django.conf import settings
from django.conf.urls.static import static


from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions
from django.conf import settings



schema_view = get_schema_view(
    openapi.Info(
        title="Shopping X API",
        default_version="v1",
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
    # url=f"http://{settings.ALLOWED_HOSTS[1]}:8080",  # Set the base URL with the port
)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('userauths.urls')),


    path('', include('userauths.api.urls')),
    path('', include('core.api.urls')),


    # Swagger documentation paths
    path('swagger<format>/', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/api/urls.py
from django.urls import path
from core.api import views



urlpatterns = [
    path("api/user/dashboard/", views.UserDashboardAPIView.as_view(), name="user-dashboard"),
    path("api/user/order-list/", views.UserOrderListAPIView.as_view(), name="user-order-list"),
    path("api/user/order-detail/", views.UserOrderDetailAPIView.as_view(), name="user-order-detail"),
]

core/urls.py
from django.urls import path
from core import views

app_name = "core"



urlpatterns = [
    path('', views.HomeTemplateView.as_view(), name="home"),
    path('store/', views.StoretemplateView.as_view(), name="store"),
    path('store/<slug:category_title>/', views.StoretemplateView.as_view(), name="products_by_category"),
    path('productdetail/<int:pk>/', views.ProductDetailView.as_view(), name="productdetail"),
    path('addtocart/', views.AddToCartTemplateView.as_view(), name="add_to_cart"),
    path('checkout/', views.CheckoutCreateView.as_view(), name="checkout"),
    path('payment/<int:pk>/', views.PaymentCreateView.as_view(), name='payment'),
    path('paymentcheckoutsession/', views.CreateCheckoutSessionView.as_view(), name="paymentcheckoutsession"),
    path('paymentsuccess/', views.PaymentSuccessView.as_view(), name="paymentsuccess"),
    path('paymentcancel/', views.PaymentCancelView.as_view(), name="paymentcancel"),
    path('payment/webhook/stripe/', views.my_webhook_view, name='webhook-stripe'),
    path('invoice/<int:pk>/', views.InvoiceDetailView.as_view(), name="invoice"),
    path('customerdashboard/', views.CustomerDashboardTemplateView.as_view(), name="customerdashboard"),
    path('customerorders/', views.CustomerOrdersListView.as_view(), name="customerorders"),
    path('customerprofile/', views.CustomerProfileTemplateView.as_view(), name="customerprofile"),
    path('customer-edit-profile/<int:pk>/', views.CustomerProfileUpdateView.as_view(), name="customer-edit-profile"),
    path('generatepdf/<int:pk>', views.GeneratePdf.as_view(), name="generatepdf"),

    #<------------------------------Ajax Urls Starts From Here------------------------------->
    path('pluscart/', views.plus_cart, name='plus-click'),
    path('minuscart/', views.minus_cart, name="minus-click"),
    path('removecart/', views.remove_cart, name="remove-cart"),
]

userauths/urls.py
from django.urls import path
from userauths import views
from userauths.forms import *

app_name = "userauths"

urlpatterns = [
    path('sign-up/', views.SignupView.as_view(), name="sign-up"),
    # path('sign-in/', views.LoginView.as_view(), name='sign-in'),
    path('accounts/login/', views.LoginView.as_view(), name="sign-in"),
    path('sign-out/', views.LogoutView.as_view(), name='sign-out'),
    path('changepassword/', views.ChangePasswordView.as_view(), name='changepassword'),
    path('passwordchangedone/', views.MyPasswordChangeDoneView.as_view(), name='passwordchangedone'),
    path('passwordreset/', views.MyPasswordResetView.as_view(), name="passwordreset"),
    path('passwordresetdone/', views.MyPasswordResetDoneView.as_view(), name='passwordresetdone'),
    path('passwordresetconfirm/<uidb64>/<token>/', views.MyPasswordResetConfirmView.as_view(), name='passwordresetconfirm'),
    path('passwordresetcomplete/', views.MyPasswordResetCompleteView.as_view(), name='passwordresetcomplete'),
    path('myadmin/', views.AdminDashboardTemplateView.as_view(), name="myadmin"),
    path('myadminprofile/', views.MyadminProfileTemplateView.as_view(), name="myadminprofile"),
    path('profileupdate/<int:pk>', views.MyadminProfileUpdateView.as_view(), name="profileupdate"),
    path('addcategory/', views.CategoryCreateView.as_view(), name="addcategory"),
    path('categorylist/', views.CategoryListView.as_view(), name="categorylist"),
    path('categoryupdate/<int:pk>/', views.CategoryUpdateView.as_view(), name="categoryupdate"),
    path('categorydelete/<int:pk>', views.CategoryDeleteView.as_view(), name="caregorydelete"),
    path('addproduct/', views.ProductCreateView.as_view(), name='addproduct'),
    path('productlist/', views.ProductListView.as_view(), name="productlist"),
    path('productupdate/<int:pk>/', views.ProductUpdateView.as_view(), name="productupdate"),
    path('productdelete/<int:pk>/', views.ProductDeleteView.as_view(), name="productdelete"),
    path('customerlist/', views.CustomerListView.as_view(), name="customerlist"),
    path('orderlist/', views.OrderListView.as_view(), name="orderlist"),
    path('invoicedetail/<int:pk>', views.MyadminInvoiceDetailView.as_view(), name="invoicedetail"),
]

core/models.py
import random
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from userauths.models import *
from django.urls import reverse

# Create your models here.


class Category(models.Model):
    title = models.CharField(max_length=100)
    category_image = models.ImageField(upload_to="category")

    def __str__(self):
        return str(self.title)
    
    class Meta:
        verbose_name_plural = "Categories"


    def get_url(self):
        return reverse("core:products_by_category", kwargs={'category_title': self.title})
         

class Product(models.Model):
    title = models.CharField(max_length=100)
    selling_price = models.FloatField()
    discounted_price = models.FloatField()
    description = models.TextField()
    brand = models.CharField(max_length=100)
    product_image = models.ImageField(upload_to="product")
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = "Products"



class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

    class Meta:
        verbose_name_plural = "Cart"



STATE_CHOICES = (
    ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'),
    ('Andhra Pradesh', 'Andhra Pradesh'),
    ('Arunachal Pradesh', 'Arunachal Pradesh'),
    ('Assam', 'Assam'),
    ('Bihar', 'Bihar'),
    ('Chandigarh', 'Chandigarh'),
    ('Chhattisgarh', 'Chhattisgarh'),
    ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'),
    ('Daman & Diu', 'Daman & Diu'),
    ('Delhi', 'Delhi'),
    ('Goa', 'Goa'),
    ('Gujarat', 'Gujarat'),
    ('Haryana', 'Haryana'),
    ('Himachal Pradesh', 'Himachal Pradesh'),
    ('Jammu & Kashmir', 'Jammu & Kashmir'),
    ('Jharkhand', 'Jharkhand'),
    ('Karnataka', 'karnataka'),
    ('Kerala', 'Kerala'),
    ('Lakshadweep', 'Lakshadweep'),
    ('Madhya Pradesh', 'Madhya Pradesh'),
    ('Maharashtra', 'Maharashtra'),
    ('Manipur', 'Manipur'),
    ('Meghalaya', 'Meghalaya'),
    ('Mizoram', 'Mizoram'),
    ('Nagaland', 'Nagaland'),
    ('Odisha', 'Odisha'),
    ('Puducherry', 'puducherry'),
    ('Punjab', 'Punjab'),
    ('Rajasthan', 'Rajasthan'),
    ('Sikkim', 'Sikkim'),
    ('Tamil Nadu', 'Tamil Nadu'),
    ('Telangana', 'Telangana'),
    ('Tripura', 'Tripura'),
    ('Uttarakhand', 'Uttarakhand'),
    ('Uttar Pradesh', 'Uttar Pradesh'),
    ('West Bengal', 'West Bengal'),
)




class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, blank=True,null=True)
    first_name = models.CharField(max_length=100,blank=True,null=True)
    last_name = models.CharField(max_length=100,blank=True,null=True)
    email = models.EmailField(max_length=150,blank=True,null=True)
    phone_number = models.IntegerField(blank=True,null=True)
    address = models.CharField(max_length=200, blank=True,null=True)
    state = models.CharField(choices=STATE_CHOICES, max_length=50)
    city = models.CharField(max_length=50)
    zipcode = models.IntegerField()

    class Meta:
        verbose_name_plural = "Orders"

    def __str__(self): 
        return str(self.id)


class OrderProduct(models.Model):
    Order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(blank=True, null=True)
    price = models.IntegerField(blank=True, null=True)
    amount = models.FloatField(blank=True,null=True)
    total_amount = models.FloatField(blank=True,null=True)


    @property
    def total_product_amount(self):
        return self.quantity * self.product.discounted_price


    class Meta:
        verbose_name_plural = "Order Products"



PAYMENT_TYPE = (
    ('Cash', 'Cash'),
    ('Card', 'Card'),
    ('Paypal', 'Paypal')
)


PAYMENT_STATUS = (
    ('Paid', 'Paid'),
    ('Not Paid', 'Not Paid')
)

class Payment(models.Model):
    payment_type = models.CharField(max_length=30, choices=PAYMENT_TYPE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    orderproduct = models.ForeignKey(OrderProduct, on_delete=models.CASCADE)
    order_id = models.IntegerField(unique=True, null=True, blank=None)
    made_on = models.DateTimeField(auto_now_add=True)
    total_amount = models.FloatField()
    payment_status = models.CharField(max_length=30, choices=PAYMENT_STATUS, default="Not Paid")


    class Meta:
        verbose_name_plural = "Payments"


    def save(self, *args, **kwargs):
        if not self.order_id:
            self.order_id = random.randint(1000, 9999)
        super().save(*args, **kwargs)

core/forms.py
from django import forms
from .models import *


class CustomerProfileForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'email', 'phone_number', 'address', 'state', 'city', 'zipcode']

    
    # def __init__(self, *args, **kwargs):
    #     super(CustomerProfileForm, self).__init__(*args, **kwargs)
                   
    #     if 'user' in self.fields:
    #         allowed_authors = User.objects.filter(is_superuser=False)
    #         self.fields['user'].queryset = allowed_authors
        

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['user', 'category', 'title', 'selling_price', 'discounted_price', 'product_image', 'description', 'brand']


    def __init__(self, *args, **kwargs):
        super(ProductForm, self).__init__(*args, **kwargs)
                   
        if 'user' in self.fields:
            allowed_authors = User.objects.filter(is_superuser=True)
            self.fields['user'].queryset = allowed_authors



class PaymentForm(forms.ModelForm):
    class Meta:
        model = Payment
        fields = ['payment_type', 'total_amount']
        widgets = {
            'payment_type': forms.Select(attrs={'class': 'form-control'}),
        }
    
    stripe_token = forms.CharField(required=False)


    def __init__(self, *args, **kwargs):
        total_amount = kwargs.pop("total_amount", None)
        super().__init__(*args, **kwargs)
        if total_amount is not None:
            self.fields['total_amount'].initial = total_amount

templates/core/addtocart.html
{% extends 'core/base.html' %}
{% load mathfilters %}

{% load static %}

{% block title %}Cart{% endblock title %}
{% block main-content %}


<section class="section-content padding-y bg">
  <div class="container">

    <!-- ============================ COMPONENT 1 ================================= -->

    <div class="row">
      {% if carts %}
      <aside class="col-lg-9">
        <div class="card">
          <table class="table table-borderless table-shopping-cart">
            <thead class="text-muted">
              <tr class="small text-uppercase">
                <th scope="col">Product</th>
                <th scope="col" width="120">Quantity</th>
                <th scope="col" width="120">Price</th>
                <th scope="col" class="text-right" width="200"> </th>
              </tr>
            </thead>
            <tbody>
              <tr>
                {% for cart in carts %}
                <td>
                  <figure class="itemside align-items-center">
                    <div class="aside"><img src="{{cart.product.product_image.url}}" class="img-sm"></div>
                    <figcaption class="info">
                      <a href="#" class="title text-dark">{{cart.product.title}}</a>
                      <p class="text-muted small"> Brand: {{cart.product.brand}}</p>
                    </figcaption>
                  </figure>
                </td>
                <td>
                  <!-- col.// -->
                  <div class="col">
                    <div class="input-group input-spinner">
                      <div class="input-group-prepend">
                        <button class="minus-cart btn btn-light" type="button" id="button-minus"
                          pid="{{cart.product.id}}"> <i class="fa fa-minus"></i> </button>
                      </div>
                      <input type="text" class="form-control" id="quantity" value="{{cart.quantity}}">
                      <div class="input-group-append">
                        <button class="plus-cart btn btn-light" type="button" id="button-plus"
                          pid="{{cart.product.id}}"> <i class="fa fa-plus"></i> </button>
                      </div>
                    </div> <!-- input-group.// -->
                  </div> <!-- col.// -->
                </td>
                <td>
                  <div class="price-wrap">
                    <var class="price">Rs.<span id="{{cart.id}}"> {{ cart.product.discounted_price |mul:cart.quantity }}
                      </span></var>
                    <small class="text-muted">Rs. {{cart.product.discounted_price}} each </small>
                  </div> <!-- price-wrap .// -->
                </td>
                <td class="text-right">
                  <a href="" class="remove-cart btn btn-danger" pid="{{cart.product.id}}"> Remove</a>
                </td>
              </tr>
              {% endfor %}

            </tbody>
          </table>
        </div> <!-- card.// -->

      </aside> <!-- col.// -->
      <aside class="col-lg-3">

        <div class="card">
          <div class="card-body">
            <dl class="dlist-align">
              <dt>Amount:</dt>
              <dd class="text-right"><b>Rs.<span id="amount"> {{amount}}</b></span></dd>
            </dl>
            <dl class="dlist-align">
              <dt>Shipping Charges:</dt>
              <dd class="text-right"><b>Rs. {{shipping_amount}}</b></dd>
            </dl>
            <hr>
            <dl class="dlist-align">
              <dt><b>Total(including VAT)</dt></b>
              <dd class="text-right text-dark b">Rs.<span id="totalamount"><strong> {{total_amount}}</span></strong>
              </dd>
            </dl>
            <br>
            <p class="text-center mb-3">
              <img src="{% static 'core/images/payavail/payments.png' %}" height="26">
            </p>
            <a href="{% url 'core:checkout' %}" class="btn btn-primary btn-block"> Checkout </a>
            <a href="{% url 'core:store' %}" class="btn btn-light btn-block">Continue Shopping</a>
          </div> <!-- card-body.// -->
        </div> <!-- card.// -->

      </aside> <!-- col.// -->
      {% else %}
      <!-- Display Empty Card Message and Image Here-->
      <div class="container my-5">
        <div class="row">
          <h3 class="text-center">You have no Product in Your Cart</h3>
          <div class="text-center">
            <img src="{% static 'core/images/emptycart.png' %}" alt="" class="img-fluid img-thumbnail w-25">
          </div>
          <div class="text-center mt-3">
            <a href="{% url 'core:store' %}" class="btn btn-primary">Continue Shopping</a>
          </div>
        </div>  
      </div>
      {% endif %}


    </div> <!-- row.// -->
    <!-- ============================ COMPONENT 1 END .// ================================= -->

  </div> <!-- container .//  -->
</section>

{% endblock main-content %}

templates/core/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <link href="{% static 'core/css/bootstrap.css' %}" rel="stylesheet" type="text/css"/>

    <!--Owl Carousel CSS-->
    <link rel="stylesheet" href="{% static 'core/css/owl.carousel.min.css' %}">
       
    <!--FontAwesome CSS-->
    <link rel="stylesheet" href="{% static 'core/css/all.min.css' %}">
    <link href="{% static 'core/fonts/fontawesome/css/min.css' %}" type="text/css" rel="stylesheet">

    <!--Custom CSS-->
    <link rel="stylesheet" href="{% static 'core/css/style.css' %}">

    <!-- custom style -->
    <link href="{% static 'core/css/ui.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'core/css/responsive.css' %}" rel="stylesheet" media="only screen and (max-width: 1200px)" />

    <!-- custom javascript -->
    <script src="{% static 'core/js/script.js' %}" type="text/javascript"></script>

    <script type="text/javascript">
      /// some script
  
      // jquery ready start
      $(document).ready(function() {
        // jQuery code
  
      }); 
      // jquery end
      </script>


    <title>ShoppingX | {% block title %} {% endblock title %} </title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
     <div class="container">
       <a class="navbar-brand" href="/">ShoppingX</a>
       <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
         <span class="navbar-toggler-icon"></span>
       </button>
       <div class="collapse navbar-collapse" id="navbarSupportedContent">
         <ul class="navbar-nav me-auto mb-2 mb-lg-0">
           <li class="nav-item">
             <a class="nav-link active" aria-current="page" href="/">Home</a>
           </li>

           <li class="nav-item dropdown">
             <a class="nav-link dropdown-toggle text-white" href="#" id="electronicsDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
               All Categories
             </a>
             <ul class="dropdown-menu" aria-labelledby="electronicsDropdown">
              <li><a class="dropdown-item">All Products</a></li>
              {% for category in categories %}
               <li><a class="dropdown-item" href="{{category.get_url}}">{{category.title}}</a></li>
               {% endfor %}
             </ul>
           </li>

           <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'core:store' %}">Store</a>
          </li>

         </ul>
         <form class="d-flex">
           <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
           <button class="btn btn-warning" type="submit">Q</button>
         </form>
         <div>
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            {% if request.user.is_authenticated %}
           <li class="nav-item dropdown mx-2">
              <a class="nav-link dropdown-toggle text-white" href="#" id="profileDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                {{request.user}}
              </a>
              <ul class="dropdown-menu" aria-labelledby="profileDropdown">
                <li><a class="dropdown-item" href="{% url 'core:customerdashboard' %}">Dashboard</a></li>
                <li><a class="dropdown-item" href="{% url 'userauths:changepassword' %}">Change Password</a></li>
                <li><a class="dropdown-item" href="{% url 'userauths:sign-out' %}">Logout</a></li>
              </ul>
            </li>
            <li class="nav-item mx-2">
             <a href="{% url 'core:add_to_cart' %}" class="nav-link text-white"><span class="badge bg-danger">{{cart_count}}</span> Cart </a>
            </li>
            {% else %}
            <li class="nav-item mx-2">
             <a href="{% url 'userauths:sign-in' %}" class="nav-link text-white">Login</a>
            </li>
            <li class="nav-item mx-2">
             <a href="{% url 'userauths:sign-up' %}" class="nav-link text-white">Registration</a>
            </li>
            {% endif %}
          </ul>
         </div>
       </div>
     </div>
    </nav>
    {% block banner_slider %} {% endblock banner_slider %}
    {% block livesale %} {% endblock livesale %}
    {% block main-content %} {% endblock main-content %}

    <!-- Start Footer -->
    <footer class="container-fluid bg-dark text-center p-2 mt-5">
        <small class="text-white">Copyright &copy; 2024 || Designed By Sarthak Shah || </small>
        <img src="{% static 'core/images/payment.png' %}" alt="" srcset="" class="img-fluid" height="2px">
    </footer> <!-- End Footer -->

    <!-- Jquery -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>

    <!-- Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

     <!-- Bootstrap JavaScript -->
     <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js"></script>

    <script src="{% static 'core/js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'core/js/all.min.js' %}"></script>
    <script src="{% static 'core/js/myscript.js' %}"></script>
  </body>
</html>

templates/core/customer-dashboard.html
{% extends 'core/base.html' %}

{% load static %}

{% block title %}Customer Dashboard Page{% endblock title %}

{% block main-content %}


<section class="section-conten padding-y bg">
    <div class="container">
        <div class="row">
            <aside class="col-md-3">
                <!--   SIDEBAR   -->
                <ul class="list-group">
                    <a class="list-group-item active" href="{% url 'core:customerdashboard' %}"> Dashboard </a>
                    <a class="list-group-item" href="{% url 'core:customerorders' %}"> My Orders </a>
                    <a class="list-group-item" href="{% url 'core:customerprofile' %}">Profile</a>
                </ul>
                <br>
                <a class="btn btn-light btn-block" href="{% url 'userauths:sign-out' %}"> <i class="fa fa-power-off"></i> <span class="text">Log out</span> </a> 
                <!--   SIDEBAR .//END   -->
            </aside>
            <main class="col-md-9">
                <article class="card">
                    <header class="card-header">
                        <strong class="d-inline-block mr-3">Logged in as: {{request.user}}</strong>
                    </header>
                    <div class="card-body">
                        <div class="row"> 
                            <div class="col-md-6">
                                <div class="card" style="text-align:center;">
                                    <div class="card-body">
                                        <h5 class="card-title">Total Orders</h5>
                                        <h4>{{total_orders}}</h4>
                                        <a href="{% url 'core:customerorders' %}">View Orders</a> 
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="card" style="text-align:center;">
                                    <div class="card-body">
                                        <img src="{{profile_picture.url}}" alt="User Profile Pic" width="50" height="50" style="border-radius:50%;">
                                        <p class="mb-0">{{email}}</p>
                                        <p>{{phone_number}}</p>
                                    </div>
                                </div>
                            </div>

                        </div> <!-- row.// -->
                    </div> <!-- card-body .// -->
                </article> <!-- order-group.// --> 
            </main>
        </div> <!-- row.// -->
    </div>
</section>


{% endblock main-content %}

templates/core/customer-orders-list.html
{% extends 'core/base.html' %}

{% load static %}

{% block title %}Customer Order List Page{% endblock title %}

{% block main-content %}


<section class="section-conten padding-y bg">
    <div class="container">
        <div class="row">
            <aside class="col-md-3">
                <!--   SIDEBAR   -->
                <ul class="list-group">
                    <a class="list-group-item" href="{% url 'core:customerdashboard' %}"> Dashboard </a>
                    <a class="list-group-item active" href=""> My Orders </a>
                    <a class="list-group-item" href="{% url 'core:customerprofile' %}">Profile</a>
                </ul>
                <br>
                <a class="btn btn-light btn-block" href="{% url 'userauths:sign-out' %}"> <i class="fa fa-power-off"></i> <span class="text">Log out</span> </a> 
                <!--   SIDEBAR .//END   --> 
            </aside>
            <main class="col-md-9">
                <article class="card">
                    <header class="card-header">
                        <h3><center><strong class="d-inline-block mr-3">Your Order History</h3></center></strong>
                    </header>
                    <div class="card-body">
                        <div class="row"> 
                            <div class="col-md-12">
                                <table class="table table-hover d-inline">
                                    <thead>
                                      <tr>
                                        <th scope="col">Order ID</th>
                                        <th scope="col">Billing Name</th>
                                        <th scope="col">Phone Number</th>
                                        <th scope="col">Order Total</th>
                                        <th scope="col">Date</th>
                                        <th scope="col">Actions</th>
                                      </tr>
                                    </thead>
                                    <tbody>
                                        {% for payment in payments %}
                                      <tr>
                                        <th scope="row">{{payment.order_id}}</th>
                                        <td>{{payment.orderproduct.Order.first_name}} {{payment.orderproduct.Order.last_name}}</td>
                                        <td>{{payment.orderproduct.Order.phone_number}}</td>
                                        <td>Rs. {{payment.orderproduct.total_amount}}</td>
                                        <td>{{payment.made_on}}</td>
                                        <td>
                                            <a href="{% url 'core:invoice' payment.pk %}"><button type="submit" class="btn btn-warning">View Details</button></a>
                                      </tr>
                                      {% endfor %}
                                      
                                      
                                    </tbody>
                                  </table> 
                            </div>

                        </div> <!-- row.// -->
                    </div> <!-- card-body .// -->
                </article> <!-- order-group.// --> 
            </main>
        </div> <!-- row.// -->
    </div>
</section>


{% endblock main-content %}

templates/core/payment-cancel.html
<h1> Cancelled Payment</h1>