E_Commerce_Website/urls.py
from django.contrib import admin
from django.urls import path, include


from django.conf import settings
from django.conf.urls.static import static


from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions
from django.conf import settings



schema_view = get_schema_view(
    openapi.Info(
        title="Shopping X API",
        default_version="v1",
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
    # url=f"http://{settings.ALLOWED_HOSTS[1]}:8080",  # Set the base URL with the port
)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('userauths.urls')),


    path('', include('userauths.api.urls')),
    path('', include('core.api.urls')),


    # Swagger documentation paths
    path('swagger<format>/', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from core import views

app_name = "core"



urlpatterns = [
    path('', views.HomeTemplateView.as_view(), name="home"),
    path('store/', views.StoretemplateView.as_view(), name="store"),
    path('store/<slug:category_title>/', views.StoretemplateView.as_view(), name="products_by_category"),
    path('productdetail/<int:pk>/', views.ProductDetailView.as_view(), name="productdetail"),
    path('addtocart/', views.AddToCartTemplateView.as_view(), name="add_to_cart"),
    path('checkout/', views.CheckoutCreateView.as_view(), name="checkout"),
    path('payment/<int:pk>/', views.PaymentCreateView.as_view(), name='payment'),
    path('paymentcheckoutsession/', views.CreateCheckoutSessionView.as_view(), name="paymentcheckoutsession"),
    path('paymentsuccess/', views.PaymentSuccessView.as_view(), name="paymentsuccess"),
    path('paymentcancel/', views.PaymentCancelView.as_view(), name="paymentcancel"),
    path('payment/webhook/stripe/', views.my_webhook_view, name='webhook-stripe'),
    path('invoice/<int:pk>/', views.InvoiceDetailView.as_view(), name="invoice"),
    path('customerdashboard/', views.CustomerDashboardTemplateView.as_view(), name="customerdashboard"),
    path('customerorders/', views.CustomerOrdersListView.as_view(), name="customerorders"),
    path('customerprofile/', views.CustomerProfileTemplateView.as_view(), name="customerprofile"),
    path('customer-edit-profile/<int:pk>/', views.CustomerProfileUpdateView.as_view(), name="customer-edit-profile"),
    path('generatepdf/<int:pk>', views.GeneratePdf.as_view(), name="generatepdf"),

    #<------------------------------Ajax Urls Starts From Here------------------------------->
    path('pluscart/', views.plus_cart, name='plus-click'),
    path('minuscart/', views.minus_cart, name="minus-click"),
    path('removecart/', views.remove_cart, name="remove-cart"),
]

userauths/api/urls.py
from django.urls import path, include
from userauths.api import views
from rest_framework.routers import DefaultRouter
from userauths.api.views import AdminCustomerViewSet, AdminOrderViewSet, AdminOrderDetailViewSet


router = DefaultRouter()
router.register(r"admin_customers", AdminCustomerViewSet, basename="customers")
router.register(r"admin_orders", AdminOrderViewSet, basename="orders")
router.register(r"admin_orders_detail", AdminOrderDetailViewSet, basename="orderdetail")


urlpatterns = [
    # User AUths Urls Starts From Here
    path("api/userauth/signup", views.SignupView.as_view(), name="signup"),
    path("api/token/", views.LoginView.as_view(), name="login"),
    path("api/token/refresh/", views.CustomTokenRefreshView.as_view(), name="token_refresh"),
    path("api/userauth/verify-email/<str:token>", views.VerifyEmailView.as_view(), name="verify-email"),
    path("api/userauth/change-password/", views.ChangePassword.as_view(), name="changepassword"),
    path("api/userauth/forgotpassword/", views.ForgetPasswordView.as_view(), name="forgotpassword",),
    path("api/userauth/reset-password/<str:token>", views.ResetPasswordView.as_view(), name="resetpassword",),
    path("api/userauth/signout/", views.SignoutView.as_view(), name="signout"),
    

    # Admin Urls Starts From Here
    path("api/admin/profile/", views.AdminProfileView.as_view(), name='admin-profile'),
    path("api/admin/dashboard/", views.AdminDasboardAPIView.as_view(), name="dashboard"),
    path("api/admin/categories/", views.AdminCategoryListCreateView.as_view(), name='admin-category-list-create'),
    path("api/admin/categories/<int:pk>/", views.AdminCategoryRetrievUpdateDeleteView.as_view(), name="admin-category-detail"),
    path("api/admin/products/", views.AdminProductListCreateView.as_view(), name='admin-product-list-create'),
    path("api/admin/products/<int:pk>/", views.AdminProductRetrieveUpdateDeletelView.as_view(), name='admin-detail'),
   
   
   
    path("api/", include(router.urls)),
]

userauths/urls.py
from django.urls import path
from userauths import views
from userauths.forms import *

app_name = "userauths"

urlpatterns = [
    path('sign-up/', views.SignupView.as_view(), name="sign-up"),
    # path('sign-in/', views.LoginView.as_view(), name='sign-in'),
    path('accounts/login/', views.LoginView.as_view(), name="sign-in"),
    path('sign-out/', views.LogoutView.as_view(), name='sign-out'),
    path('changepassword/', views.ChangePasswordView.as_view(), name='changepassword'),
    path('passwordchangedone/', views.MyPasswordChangeDoneView.as_view(), name='passwordchangedone'),
    path('passwordreset/', views.MyPasswordResetView.as_view(), name="passwordreset"),
    path('passwordresetdone/', views.MyPasswordResetDoneView.as_view(), name='passwordresetdone'),
    path('passwordresetconfirm/<uidb64>/<token>/', views.MyPasswordResetConfirmView.as_view(), name='passwordresetconfirm'),
    path('passwordresetcomplete/', views.MyPasswordResetCompleteView.as_view(), name='passwordresetcomplete'),
    path('myadmin/', views.AdminDashboardTemplateView.as_view(), name="myadmin"),
    path('myadminprofile/', views.MyadminProfileTemplateView.as_view(), name="myadminprofile"),
    path('profileupdate/<int:pk>', views.MyadminProfileUpdateView.as_view(), name="profileupdate"),
    path('addcategory/', views.CategoryCreateView.as_view(), name="addcategory"),
    path('categorylist/', views.CategoryListView.as_view(), name="categorylist"),
    path('categoryupdate/<int:pk>/', views.CategoryUpdateView.as_view(), name="categoryupdate"),
    path('categorydelete/<int:pk>', views.CategoryDeleteView.as_view(), name="caregorydelete"),
    path('addproduct/', views.ProductCreateView.as_view(), name='addproduct'),
    path('productlist/', views.ProductListView.as_view(), name="productlist"),
    path('productupdate/<int:pk>/', views.ProductUpdateView.as_view(), name="productupdate"),
    path('productdelete/<int:pk>/', views.ProductDeleteView.as_view(), name="productdelete"),
    path('customerlist/', views.CustomerListView.as_view(), name="customerlist"),
    path('orderlist/', views.OrderListView.as_view(), name="orderlist"),
    path('invoicedetail/<int:pk>', views.MyadminInvoiceDetailView.as_view(), name="invoicedetail"),
]

userauths/api/views.py
from drf_yasg.utils import swagger_auto_schema
from rest_framework import generics, serializers, status, viewsets, filters
from rest_framework.parsers import FormParser, MultiPartParser
from rest_framework.permissions import AllowAny, IsAuthenticated
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework_simplejwt.tokens import AccessToken
from rest_framework_simplejwt.views import TokenRefreshView
from drf_yasg import openapi
from E_Commerce_Website.app_helpers import CustomResponse
from userauths.api import serializers as userauths_serializer
from userauths.models import User
from django.shortcuts import render
from django.contrib import messages
from django.views import View
from userauths.api.forms import ResetPasswordForm
from django.core.mail import send_mail
import uuid
from django.conf import settings
from userauths.models import *
from E_Commerce_Website.permissions import IsSuperuser
from core.models import *
from userauths.models import *
from django.db.models import Q
from userauths.api import pagination
from django_filters.rest_framework import DjangoFilterBackend
from datetime import datetime
from rest_framework.filters import OrderingFilter



#<---------------------------------User Auths Starts From Here---------------------------->

#<---------------------------------Signup View Starts From Here---------------------------->
class SignupView(generics.CreateAPIView):
    """
    View for handling user signup.
    """
    permission_classes = [AllowAny]
    serializer_class = userauths_serializer.UserSerializer    # Ensure this serializer handles User creation

    @swagger_auto_schema(
        operation_description="User signup endpoint",
        responses={201: "User created successfully", 400: "Bad request"},
        tags=["UserAuth API"],
    )
    def post(self, request, *args, **kwargs):
        """
        Custom post method to handle user signup.
        """
        try:
            serializer = self.get_serializer(data=request.data) # Retrieves an instance of the UserSerializer with the data from the request (request.data).
            serializer.is_valid(raise_exception=True)            # Validates the input data against the rules defined in the UserSerializer
                                                                 # f the data is invalid: A serializers.ValidationError is raised, which will be handled in the except block

            serializer.save()                                # Creates a new user in the database using the validated data.

            return CustomResponse.success(                   # Return a success response
                message="Email verification link sent on your email id."
            )
        except serializers.ValidationError as e:                 # Handle validation errors
            # Extract the first error message from the dictionary
            error_messages = []
            for field, messages in e.detail.items():
                if isinstance(messages, list):
                    error_messages.extend(messages)
                else:
                    error_messages.append(messages)

             # Return only the first error message if there are multiple
            return CustomResponse.error(
                message=error_messages[0] if error_messages else "Validation error."
            )
    
        except Exception as e:                                   # Handle any other exceptions
            return CustomResponse.error(
                message=f"An unexpected error occurred: {str(e)}"
            )
        
#<---------------------------------Login API View Starts From Here------------------------------>
class LoginView(generics.GenericAPIView):
    permission_classes = [AllowAny]
    serializer_class = userauths_serializer.CustomTokenObtainPairSerializer


    def post(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)    # Prepares the serializer to validate the input data (e.g., email, password).
        try:
            serializer.is_valid(raise_exception=True)         # Validates the input data against the rules defined in the serializer.
            return CustomResponse.success(
                message=serializer.validated_data["message"],  # Extracts the "message" key from the serializer's validated_data, which likely contains a login success message.    
                data=serializer.validated_data["data"],        # Extracts the "data" key from the serializer's validated_data, which might include: Access and refresh tokens, User information like email, name, etc.
            )
        except serializers.ValidationError as e:    # Catches validation errors raised by the serializer.is_valid() method. This exception occurs if:-  The login credentials are incorrect. Required fields (e.g., email or password) are missing. Other validation rules in the serializer fail.
            error_message = e.detail.get("message", ["Validation error."])[0]
            return CustomResponse.error(
                message=error_message
            )

'''
e.detail:
Contains the error details as a dictionary. For example:
{"message": ["Invalid credentials."]}
get("message", ["Validation error."]):
Tries to fetch the "message" key from the error details.
If "message" is not present, defaults to ["Validation error."].
[0]:
Extracts the first message from the list of error messages.

CustomResponse.error:
Returns a standardized error response.
Message:
Uses the extracted error_message to inform the client about what went wrong.
Example: "Invalid credentials."

'''


#<--------------------------------VerifyEmailView Starts From Here----------------------------->
class VerifyEmailView(generics.GenericAPIView):
    permission_classes = [AllowAny]

    @swagger_auto_schema(
        operation_description="User Email Verification",
        responses={404: "Token not found", 200: "Email verified successfully"},
        tags=["UserAuth API"],
    )
    def get(self, request, token, *args, **kwargs):
        try:
            # Search for the user with the given token
            user = User.objects.filter(email_token=token).first()   # Looks for a user in the User model whose email_token matches the provided token and returns a queryset of all matching with the first users in the queryset or None if no match found
            print('user: ', user)

            if not user:                 # If no user is found (user is None), it means the token is invalid or expired.
                return render(
                    request, "api/token_not_found.html", status=status.HTTP_404_NOT_FOUND   # Renders the token_not_found.html template with a 404 Not Found status.
                )
            print(">>>>>>>>>>>>>>>>>>>>>.")
            # Check if the user is already verified
            if user.email_verified:
                # Render the `email_verified.html` template with a custom message for already-verified users
                return render(
                    request,
                    "api/email_verified.html",
                    {"message": "Your email has already been verified."}
                )

            # Set email as verified and save the user
            user.email_verified = True                 # Sets the email_verified field of the user object to True.
            user.save()                                # Persists the changes to the database
            print("---------------------")

            return render(
                request,
                "api/email_verified.html",
                {"message": "Email verified successfully!"},
            )

        except Exception as e:
            # Log the exception for debugging purposes
            print(f"Error verifying email: {e}")
            # Use CustomResponse without the `status` argument
            return CustomResponse.error(message="Server error")



#<---------------------Refresh Token View Starts From Here------------------------------->
class CustomTokenRefreshView(TokenRefreshView):
    def post(self, request, *args, **kwargs):   # Overrides the post method of the parent TokenRefreshView class to customize the response.
        # Call the parent class's post method to get the original response
        response = super().post(request, *args, **kwargs)

        if response.status_code == 200:
            return CustomResponse.success(
                message="Access token generated",
                data={"access_token": response.data.get("access")},
            )

        return CustomResponse
    

#<--------------------------Change Password View Starts From Here---------------------------->
class ChangePassword(generics.GenericAPIView):
    serializer_class = userauths_serializer.ChangePasswordSerializer
    Permission_classes = [IsAuthenticated]


    @swagger_auto_schema(
        operation_description="partial update description override",
        responses={404: "slug not found", 200: "not found"},
        tags=["UserAuth API"],
    )
    def post(self, request, *args, **kwargs):
        try:
            user = request.user    # Retrieves the currently authenticated user making the request
            serializer = self.get_serializer(data=request.data, context={"user": user})   # Creates an instance of the ChangePasswordSerializer and passes the user's data (request.data) for validation. Adds the currently authenticated user (user) to the serializer's context for custom validation logic

            serializer.is_valid(raise_exception=True)   # Validates the data passed to the serializer. If validation fails, it raises a serializers.ValidationError.

            # user = request.user
            user.set_password(serializer.validated_data["password"])  # Uses the set_password method of the User model to securely hash and update the user's password. serializer.validated_data["password"]:- Retrieves the validated new password from the serializer.

templates/userauths/add-category.html
{% extends 'userauths/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
<div class="page-wrapper">
    <div class="content container-fluid">
        <div class="page-header">
            <div class="row align-items-center">
                <div class="col">
                    <h3 class="page-title mt-5">Add Category</h3> </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <form class="add room" method="POST" enctype="multipart/form-data"> {% csrf_token %}
                    <div class="row formtype">
                        <div class="col-md-4">
                            <div class="form-group">
                                {{form.title | as_crispy_field}}
                            </div>
                        </div>

                        <div class="col-md-4">
                            <div class="form-group">
                               {{form.category_image | as_crispy_field}}
                            </div>
                        </div>
                        </div>
                    </div>
                        <a href=""><button type="submit" class="btn btn-primary buttonedit ml-3">Save</button></a>
                        <a href="{% url 'userauths:categorylist' %}">
                            <button type="button" class="btn btn-warning buttonedit ml-3">Cancel</button>
                        </a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
</div>
{% endblock %}

templates/userauths/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
	<title>Admin ShoppingX Dashboard Template</title>  
	<link rel="shortcut icon" type="image/x-icon" href="{% static 'myadmin/assets/img/favicon.png' %}">
	<link rel="stylesheet" href="{% static 'userauths/assets/css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'userauths/assets/plugins/fontawesome/css/fontawesome.min.css' %}">
	<link rel="stylesheet" href="{% static 'userauths/assets/plugins/fontawesome/css/all.min.css' %}">
	<link rel="stylesheet" href="{% static 'userauths/assets/css/feathericon.min.css' %}">
	<link rel="stylehseet" href="{% static 'userauths/https://cdn.oesmith.co.uk/morris-0.5.1.css' %}">
	<link rel="stylesheet" href="{% static 'userauths/assets/plugins/morris/morris.css' %}">
	<link rel="stylesheet" href="{% static 'userauths/assets/css/style.css' %}"> </head>

<body>
	<div class="main-wrapper">
		<div class="header">
			<div class="header-left">
				<a href="index.html" class="logo"> <img class="rounded-circle" src="{{profile_picture.url}}" width="50" height="70" alt="logo"> <span class="logoclass">ShoppingX</span> </a>
				<a href="index.html" class="logo logo-small"> <img src="{{profile_picture.url}}" alt="Logo" width="30" height="30"> </a>
			</div>
			<a href="javascript:void(0);" id="toggle_btn"> <i class="fe fe-text-align-left"></i> </a>
			<a class="mobile_btn" id="mobile_btn"> <i class="fas fa-bars"></i> </a>
			<ul class="nav user-menu">
				<li class="nav-item dropdown has-arrow">
					<a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown"> <span class="user-img"><img class="rounded-circle" src="{{profile_picture.url}}" width="31" alt=""></span> </a>
					<div class="dropdown-menu">
						<div class="user-header">
							  <div class="avatar avatar-sm"> <img src="{{profile_picture.url}}" alt="User Image" class="avatar-img rounded-circle"> </div>
							   <div class="user-text">     
								<h6>{{user.first_name}} {{user.last_name}}</h6>
								<p class="text-muted mb-0">Administrator</p>
							</div>
						</div> <a class="dropdown-item" href="{% url 'userauths:myadminprofile' %}">My Profile</a>
                        <a class="dropdown-item" href="{% url 'userauths:sign-out' %}">Logout</a> </div>
				</li>
			</ul>
		</div>
		<div class="sidebar" id="sidebar">
			<div class="sidebar-inner slimscroll">
				<div id="sidebar-menu" class="sidebar-menu">
					<ul>
						<li class="active"> <a href="{% url 'userauths:myadmin' %}"><i class="fas fa-tachometer-alt"></i> <span>Dashboard</span></a> </li>
						<li class="list-divider"></li> 
						<li class="submenu"> <a href="#"><i class="fas fa-layer-group"></i> <span> Category </span> <span class="menu-arrow"></span></a>
							<ul class="submenu_class" style="display: none;">
								<li><a href="{% url 'userauths:categorylist' %}"> All Categories </a></li>	
								<li><a href="{% url 'userauths:addcategory' %}"> Add Categories </a></li>
							</ul>
						</li>
						<li class="submenu"> <a href="#"><i class="fab fa-product-hunt"></i> <span> Products </span> <span class="menu-arrow"></span></a>
							<ul class="submenu_class" style="display: none;">
								<li><a href="{% url 'userauths:productlist' %}"> All Products </a></li>
								<li><a href="{% url 'userauths:addproduct' %}"> Add Products </a></li>
							</ul>
						</li>
						<li class="submenu"> <a href="#"><i class="fas fa-user"></i> <span> Customers </span> <span class="menu-arrow"></span></a>
							<ul class="submenu_class" style="display: none;">
								<li><a href="{% url 'userauths:customerlist' %}"> All customers </a></li>
							</ul>
						</li>
						<li class="submenu"> <a href="#"><i class="fas fa-shopping-cart"></i> <span> Orders </span> <span class="menu-arrow"></span></a>
							<ul class="submenu_class" style="display: none;">
								<li><a href="{% url 'userauths:orderlist' %}">All orders </a></li>
					
						</li>
							</ul>
						</li>
					</ul>
				</div>
			</div>
		</div>
{% block content %}

{% endblock %}
<script data-cfasync="false" src="{% static 'userauths/../../../cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js' %}"></script>
	<script src="{% static 'userauths/assets/js/jquery-3.5.1.min.js' %}"></script>
	<script src="{% static 'userauths/assets/js/popper.min.js' %}"></script>
	<script src="{% static 'userauths/assets/js/bootstrap.min.js' %}"></script>
	<script src="{% static 'userauths/assets/plugins/slimscroll/jquery.slimscroll.min.js' %}"></script>
	<script src="{% static 'userauths/assets/plugins/raphael/raphael.min.js' %}"></script>
	<script src="{% static 'userauths/assets/plugins/morris/morris.min.js' %}"></script>
	<script src="{% static 'userauths/assets/js/chart.morris.js' %}"></script>
	<script src="{% static 'userauths/assets/js/script.js' %}"></script>
</body>
</html>

templates/userauths/delete-category.html
{% extends 'userauths/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
<div class="page-wrapper">
    <div class="content container-fluid">
        <div class="page-header"></div>
        <div class="modal-content">
            <form action="" method="POSt" enctype="multipart/form-data"> {% csrf_token %}
            <div class="modal-body text-center"> <img src="{% static 'userauths/assets/img/sent.png' %}" alt="" width="50" height="46">
                <h3 class="delete_class">Are you sure want to delete this Asset?</h3>
                <div class="m-t-20"> <a href="{% url 'userauths:categorylist' %}" class="btn btn-white" data-dismiss="modal">Close</a>
                    <a href="{% url 'userauths:categorylist' %}"><button type="submit" class="btn btn-danger">Yes</button></a>
                </form>
        </div> 
    </div>
    </div>
</div>
</div>
{% endblock %}

templates/userauths/password-change.html
{% extends 'core/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Buy Now{% endblock title %}
{% block main-content %}
<div class="container my-5">
 <div class="row">
 <h3>Welcome {{request.user}}</h3>
  <div class="col-sm-2 border-end">
   <ul class="list-unstyled">
    <li class="d-grid"><a href="" class="btn btn-primary">Change Password</a></li>
   </ul>
  </div>
  <div class="col-sm-9 offset-sm-1">
   <form method="post" novalidate class="shadow p-5">
     {% csrf_token %}
     {{ form|crispy }}
     <button type="submit" class="btn btn-primary">Submit</button>
   </form>
  </div>
 </div>
</div>
{% endblock main-content %}

templates/userauths/password-reset-complete.html
{% extends 'core/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Password Reset Complete{% endblock title %}
{% block main-content %}
<div class="container">
 <div class="row my-3">
  <div class="col-sm-6 offset-sm-3">
    <h4>Reset Password Completed !!</h4>

    <h3>Password Changed Successfully !!</h3>
    <iframe src="https://giphy.com/embed/tf9jjMcO77YzV4YPwE" width="480" height="480" frameBorder="0" class="giphy-embed" allowFullScreen></iframe>
   <form method="post" novalidate class="shadow p-5">
  </div>
 </div>
</div>
{% endblock main-content %}

templates/userauths/product-list.html
{% extends 'userauths/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}

<div class="page-wrapper">
    <div class="content container-fluid">
        <div class="page-header">
            <div class="row align-items-center">
                <div class="col">
                    <div class="mt-5">
                        <h4 class="card-title float-left mt-2">All Products</h4>
                        <a href="{% url 'userauths:addproduct' %}" class="btn btn-primary float-right veiwbutton">Add Product</a>
                    </div>
                    <div class="row mt-3">
                        <div class="col-5 offset-1 d-flex justify-content-center">
                            <form method="GET" action="">
                                <div class="input-group">
                                    <input class="form-control mr-sm-2" type="text" name="search" placeholder="Search" aria-label="Search">
                                    <div class="input-group-append">
                                        <button class="btn btn-outline-success" type="submit">Search</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                    <div class="row mt-3">
                        <div class="col-3">
                            <!-- Your content for All Category goes here -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
<div class="row">
    <div class="col-sm-12">
        <div class="card card-table">
            <div class="card-body booking_card">
                <div class="table-responsive">
                    <table class="datatable table table-stripped table table-hover table-center mb-1">
                        <thead class="table-primary">
                            <tr>
                                <th>Product ID</th>
                                <th>User</th>
                                <th>Category Name</th>
                                <th>Product Title</th>
                                <th>Image</th>
                                <th>Selling Price</th>
                                <th>Discounted Price</th>
                                <th>Description</th>
                                <th>Brand</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for product in products %}
                            <tr>
                                <td>{{product.id}}</td>
                                <th>{{product.user.username}}</td>
                                <td>{{product.category.title}}</td>
                                <td>{{product.title}}</td>
                                <td><img src="/media/{{product.product_image}}"style="height: 70px; width: 70px; border-radius: 10px";></td>
                                <td>{{product.selling_price}}</td>
                                <td>{{product.discounted_price}}</td>
                                <td>{{product.description}}</td>
                                <td>{{product.brand}}</td>
                                <td>
                                    <a href="{% url 'userauths:productupdate' product.pk %}"><button type="submit" class="btn btn-warning">Update</button></a>
                                    <a href="{% url 'userauths:productdelete' product.pk %}"><button type="submit" class="btn btn-danger ml-1">Delete</button></a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
</div>
{% endblock %}

templates/userauths/sign-in.html
{% extends 'core/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Login{% endblock title %}

{% block main-content %}
<div class="container">
 <div class="row my-3">
  <div class="col-sm-6 offset-sm-3">
   <h3><center>Login</h3></center>
   <hr>

   <div class="text-center"> <!-- Added text-center class here -->
    {% if messages %}
    <div class="messages">
      {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
          {{ message }}
        </div>
      {% endfor %}
    </div>
    {% endif %}
    </div>

   <form action="" method="POST" novalidate class="shadow p-5">
    {% csrf_token %}
    {{ form|crispy }}

    <small><b><a href="{% url 'userauths:passwordreset' %}">Forgot Password ?</a></small></b><br>
    <button type="submit" class="btn btn-primary mt-4">Login</button>
    <br>
    <div class="text-center text-primary fw-bold"><small><b>New to ShoppinglyX ? <a href="{% url 'userauths:sign-up' %}"
       class="text-danger">Create an Account</a> </small></b></div>
   </form>
  </div>
 </div>
</div>
{% endblock main-content %}